name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: |
          uv sync --dev
          
      - name: Run ruff check
        run: uv run ruff check src/
        
      - name: Run ruff format check
        run: uv run ruff format --check src/
        
      - name: Run pyright type check
        run: uv run pyright src/

  test:
    name: Test Basic Functionality
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: uv sync
        
      - name: Test CLI help
        run: |
          uv run arxiv-search --help
          uv run arxiv-search search --help
          uv run arxiv-search harvest --help
          
      - name: Test harvest command (basic functionality)
        run: |
          # Test harvest command with a small date range
          timeout 30s uv run arxiv-search harvest --from-date 2024-01-01 --until-date 2024-01-01 | head -1 | jq .
        continue-on-error: true  # ArXiv API might be flaky