name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # Required for trusted publishing to PyPI
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: uv sync --dev
        
      - name: Run lints and type checks
        run: |
          uv run ruff check src/
          uv run ruff format --check src/
          uv run pyright src/
          
      - name: Test CLI help
        run: |
          uv run arxiv-search --help
          uv run arxiv-search search --help
          uv run arxiv-search harvest --help
      
      - name: Build package
        run: uv build
        
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Uses PyPI trusted publishing - no API token needed
          # Must be configured at https://pypi.org/manage/account/publishing/
          skip-existing: true  # Skip if version already exists